version: "3"
services:
  front:
    build: ./front/
    networks:
      - ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aml-sms-builder.rule=Host(`aml.adrienvh.fr`)"
      - "traefik.http.routers.aml-sms-builder.entrypoints=websecure"
      - "traefik.http.routers.aml-sms-builder.tls.certresolver=letsencrypt"
networks:
  ingress:
    name: gateway_ingress
    external: true